# Runs the server in a linux-amd64 container with debug port exposed
# Used in debugging solidity linux-amd64 binary executables  
version: "3.7"

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

networks:
  source-verify:

services:
  server:
    <<: *project-base
    # image: ethereum/source-verify:server-${TAG}
    build:
      context: ../
      dockerfile: src/Dockerfile.server.debug
    container_name: server-${TAG}
    platform: linux/amd64
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
      - "9229:9229"      # Debug port
    volumes:
      - ../:/home/app
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
      - type: bind
        source: $SOLC_REPO_HOST
        target: $SOLC_REPO
      - type: bind
        source: $SOLJSON_REPO_HOST
        target: $SOLJSON_REPO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 10
